// Code generated by go_code.py; DO NOT EDIT.

package desktop_ui
import "fmt"
import "github.com/kovidgoyal/kitty/tools/cli"
var _ = fmt.Sprintf
func create_cmd(root *cli.Command, run_func func(*cli.Command, *Options, []string)(int, error)) {
ans := root.AddSubCommand(&cli.Command{
Name: "desktop_ui",
Run: func(cmd *cli.Command, args []string) (int, error) {
opts := Options{}
err := cmd.GetOptionValues(&opts)
if err != nil { return 1, err }
return run_func(cmd, &opts, args)},
Hidden: true,
})
specialize_command(ans)
clone := root.AddClone(ans.Group, ans)
clone.Hidden = false
clone.Name = "desktop-ui"
}
type Options struct {

}
func (opts Options) AsCommandLine() (ans []string) {
return
}
