// Code generated by go_code.py; DO NOT EDIT.

package vt

// Total number of bits used: 25
type CellColor uint32

func (s CellColor) Blue() uint8 {
    return uint8(s & 0b11111111)
}

func (s *CellColor) Set_blue(val uint8) {
    *s &^= 0b11111111
    *s |= CellColor(val & 0b11111111)
}

func (s CellColor) Green() uint8 {
    return uint8((s >> 8) & 0b11111111)
}

func (s *CellColor) Set_green(val uint8) {
    *s &^= 0b11111111 << 8
    *s |= CellColor(val&0b11111111) << 8
}

func (s CellColor) Red() uint8 {
    return uint8((s >> 16) & 0b11111111)
}

func (s *CellColor) Set_red(val uint8) {
    *s &^= 0b11111111 << 16
    *s |= CellColor(val&0b11111111) << 16
}

func (s CellColor) Is_idx() uint8 {
    return uint8((s >> 24) & 0b1)
}

func (s *CellColor) Set_is_idx(val uint8) {
    *s &^= 0b1 << 24
    *s |= CellColor(val&0b1) << 24
}

