// Code generated by go_code.py; DO NOT EDIT.

package vt

// Total number of bits used: 32
type Ch uint32

func (s Ch) Ch_or_idx() uint32 {
    return uint32(s & 0b1111111111111111111111111111111)
}

func (s *Ch) Set_ch_or_idx(val uint32) {
    *s &^= 0b1111111111111111111111111111111
    *s |= Ch(val & 0b1111111111111111111111111111111)
}

func (s Ch) Is_idx() uint8 {
    return uint8((s >> 31) & 0b1)
}

func (s *Ch) Set_is_idx(val uint8) {
    *s &^= 0b1 << 31
    *s |= Ch(val&0b1) << 31
}

