// Generated by generate.go do not edit
//go:build amd64

package simdstring

// Test loading of vector register
//
//go:noescape
func test_load_asm_128(src []byte, ans []byte)

// Test broadcast of byte into vector
//
//go:noescape
func test_set1_epi8_asm_128(b uint8, ans []byte)

// Test byte comparison of two vectors
//
//go:noescape
func test_cmpeq_epi8_asm_128(a []byte, b []byte, ans []byte)

// Test byte comparison of two vectors
//
//go:noescape
func test_cmplt_epi8_asm_128(a []byte, b []byte, which int, ans []byte)

// Test OR of two vectors
//
//go:noescape
func test_or_asm_128(a []byte, b []byte, ans []byte)

// Test jump on zero register
//
//go:noescape
func test_jump_if_zero_asm_128(a []byte) (ans int)

// Test counting bytes to first match
//
//go:noescape
func test_count_to_match_asm_128(a []byte, b uint8) (ans int)

