// Generated by generate.go do not edit
//go:build arm64

package simdstring

// Test loading of vector register
//
func test_load_asm_256(src []byte, ans []byte){
panic("No SIMD implementations for this function")
}

// Test broadcast of byte into vector
//
func test_set1_epi8_asm_256(b uint8, ans []byte){
panic("No SIMD implementations for this function")
}

// Test byte comparison of two vectors
//
func test_cmpeq_epi8_asm_256(a []byte, b []byte, ans []byte){
panic("No SIMD implementations for this function")
}

// Test byte comparison of two vectors
//
func test_cmplt_epi8_asm_256(a []byte, b []byte, which int, ans []byte){
panic("No SIMD implementations for this function")
}

// Test OR of two vectors
//
func test_or_asm_256(a []byte, b []byte, ans []byte){
panic("No SIMD implementations for this function")
}

// Test jump on zero register
//
func test_jump_if_zero_asm_256(a []byte) (ans int){
panic("No SIMD implementations for this function")
}

// Test counting bytes to first match
//
func test_count_to_match_asm_256(a []byte, b uint8) (ans int){
panic("No SIMD implementations for this function")
}

