// Generated by generate.go do not edit
//go:build !(amd64||arm64)

package simdstring

const HasSIMD256Code = false
// Find the index of either of two bytes
//
func index_byte2_asm_256(data []byte, b1 uint8, b2 uint8) (ans int){
panic("No SIMD implementations for this function")
}

// Find the index of either of two bytes
//
func index_byte2_string_asm_256(data string, b1 uint8, b2 uint8) (ans int){
panic("No SIMD implementations for this function")
}

// Find the index of a C0 control code
//
func index_c0_asm_256(data []byte) (ans int){
panic("No SIMD implementations for this function")
}

// Find the index of a C0 control code
//
func index_c0_string_asm_256(data string) (ans int){
panic("No SIMD implementations for this function")
}

// Find the index of a byte
//
func index_byte_asm_256(data []byte, b uint8) (ans int){
panic("No SIMD implementations for this function")
}

// Find the index of a byte
//
func index_byte_string_asm_256(data string, b uint8) (ans int){
panic("No SIMD implementations for this function")
}

// Find the index of the first byte that is not b
//
func not_index_byte_asm_256(data []byte, b uint8) (ans int){
panic("No SIMD implementations for this function")
}

// Find the index of the first byte that is not b
//
func not_index_byte_string_asm_256(data string, b uint8) (ans int){
panic("No SIMD implementations for this function")
}

// Find the index of the first byte that is neither b1 nor b2
//
func not_index_byte2_asm_256(data []byte, b1 uint8, b2 uint8) (ans int){
panic("No SIMD implementations for this function")
}

// Find the index of the first byte that is neither b1 nor b2
//
func not_index_byte2_string_asm_256(data string, b1 uint8, b2 uint8) (ans int){
panic("No SIMD implementations for this function")
}

