// Generated by generate.go do not edit
//go:build amd64

package simdstring

const HasSIMD256Code = true
// Find the index of either of two bytes
//
//go:noescape
func index_byte2_asm_256(data []byte, b1 uint8, b2 uint8) (ans int)

// Find the index of either of two bytes
//
//go:noescape
func index_byte2_string_asm_256(data string, b1 uint8, b2 uint8) (ans int)

// Find the index of a C0 control code
//
//go:noescape
func index_c0_asm_256(data []byte) (ans int)

// Find the index of a C0 control code
//
//go:noescape
func index_c0_string_asm_256(data string) (ans int)

// Find the index of a byte
//
//go:noescape
func index_byte_asm_256(data []byte, b uint8) (ans int)

// Find the index of a byte
//
//go:noescape
func index_byte_string_asm_256(data string, b uint8) (ans int)

// Find the index of the first byte that is not b
//
//go:noescape
func not_index_byte_asm_256(data []byte, b uint8) (ans int)

// Find the index of the first byte that is not b
//
//go:noescape
func not_index_byte_string_asm_256(data string, b uint8) (ans int)

// Find the index of the first byte that is neither b1 nor b2
//
//go:noescape
func not_index_byte2_asm_256(data []byte, b1 uint8, b2 uint8) (ans int)

// Find the index of the first byte that is neither b1 nor b2
//
//go:noescape
func not_index_byte2_string_asm_256(data string, b1 uint8, b2 uint8) (ans int)

