// Code generated by go_code.py; DO NOT EDIT.

package command_palette
import "fmt"
import "github.com/kovidgoyal/kitty/tools/cli"
var _ = fmt.Sprintf
func create_cmd(root *cli.Command, run_func func(*cli.Command, *Options, []string)(int, error)) {
ans := root.AddSubCommand(&cli.Command{
Name: "command_palette",
ShortDescription: "Browse and trigger keyboard shortcuts and actions",
HelpText: "Browse and trigger keyboard shortcuts and actions",
Run: func(cmd *cli.Command, args []string) (int, error) {
opts := Options{}
err := cmd.GetOptionValues(&opts)
if err != nil { return 1, err }
return run_func(cmd, &opts, args)},
Hidden: true,
})
clone := root.AddClone(ans.Group, ans)
clone.Hidden = false
clone.Name = "command-palette"
}
type Options struct {

}
func (opts Options) AsCommandLine() (ans []string) {
return
}
