// Code generated by go_code.py; DO NOT EDIT.

package command_palette
import "fmt"
import "strconv"
import "github.com/kovidgoyal/kitty/tools/config"
import "github.com/kovidgoyal/kitty/tools/utils/style"
var _ = fmt.Println
var _ = config.StringToBool
var _ = strconv.Atoi
var _ = style.ParseColor
type Config struct {
KeyboardShortcuts []*config.KeyAction
}
func NewConfig() *Config {
return &Config{
KeyboardShortcuts: []*config.KeyAction{
{Name: "selection_up", Args: "", AllowFallback: "shifted,alternate", Normalized_keys: []string{
"ctrl+k",
}},
{Name: "selection_up", Args: "", AllowFallback: "shifted,alternate", Normalized_keys: []string{
"ctrl+p",
}},
{Name: "selection_down", Args: "", AllowFallback: "shifted,alternate", Normalized_keys: []string{
"ctrl+j",
}},
{Name: "selection_down", Args: "", AllowFallback: "shifted,alternate", Normalized_keys: []string{
"ctrl+n",
}},
},
}}
func (c *Config) Parse(key, val string) (err error) {
switch key {
default: return fmt.Errorf("Unknown configuration key: %#v", key)
case "map":
tempsc, err := config.ParseMap(val)
if err != nil { return fmt.Errorf("Failed to parse map = %#v with error: %w", val, err) }
c.KeyboardShortcuts = append(c.KeyboardShortcuts, tempsc)
}
return}
