// Code generated by go_code.py; DO NOT EDIT.

package dnd
import "fmt"
import "github.com/kovidgoyal/kitty/tools/cli"
var _ = fmt.Sprintf
func create_cmd(root *cli.Command, run_func func(*cli.Command, *Options, []string)(int, error)) {
ans := root.AddSubCommand(&cli.Command{
Name: "dnd",
ShortDescription: "Perform drag and drop operations, even over SSH",
Usage: "[options] [files to drag]",
HelpText: "Perform drag and drop operations, even over SSH.\n\nAny arguments on the command line are assumed to be files and directories to drag.\nThey will be dragged as the text/uri-list MIME type which can then be dropped into any\nfile manager or similar program to copy the files.\n\nIf the text/uri-list MIME type is dropped onto this window, the files and directories in it are\ncopied into the current working directory. When dragging from this window, if a move operation is\nperformed when dropping and the drop is to a remote machine, the files and directories to drag and deleted.\n\nIf data is present on STDIN it is set as text/plain when dragging, unless text/plain is specified via --drag.\nAny text/plain data that is dropped onto this window is output to STDOUT, if STDOUT is connected to a file, otherwise it\nis discarded.\n\nPress the Esc or Ctrl+C keys to quit the kitten at any time, cancelling any in progress drag.\n",
Run: func(cmd *cli.Command, args []string) (int, error) {
opts := Options{}
err := cmd.GetOptionValues(&opts)
if err != nil { return 1, err }
return run_func(cmd, &opts, args)},
})
ans.Add(cli.OptionSpec{
            Name: "--drag",
            Type: "list",
            Dest: "Drag",
            Help: "When starting a drag, use the specified file as the data source for the specified MIME type. Syntax is: mime-type:path/to/file. For example image/jpeg:mypic.jpg Can be specified multiple times to drag multiple MIME types.",
        })
ans.Add(cli.OptionSpec{
            Name: "--drop",
            Type: "list",
            Dest: "Drop",
            Help: "When receiving a drop, use the specified file as the data destination for the specified MIME type. Syntax is: mime-type:path/to/file. For example image/jpeg:mypic.jpg Can be specified multiple times to enable receiving multiple MIME types. If no path is specified, it will prevent that MIME type being dropped, useful to disable accepting text/plain and text/uri-list.",
        })
ans.Add(cli.OptionSpec{
            Name: "--drop-dest",
            Type: "",
            Dest: "DropDest",
            Help: "Path to the directory in which dropped data is saved. Defaults to the current working directory.",
        })
ans.Add(cli.OptionSpec{
            Name: "--confirm-drop-overwrite",
            Type: "bool-set",
            Dest: "ConfirmDropOverwrite",
            Help: "Ask for confirmation when dropping text/uri-list data if the drop will cause any existing files to be overwritten. Note that confirmation is asked only for actual file conflicts, non conflicting files are automatically created.",
        })
ans.Add(cli.OptionSpec{
            Name: "--drop-anywhere",
            Type: "choices",
            Dest: "DropAnywhere",
            Help: "Allow dropping anywhere, not just on the Copy or Move drop regions. Dropping anywhere will perform the specified action.",
        
Choices: "disallowed, copy, move",

Completer: cli.NamesCompleter("Choices for drop-anywhere", "disallowed", "copy", "move"),
	Default: "disallowed",
})
ans.Add(cli.OptionSpec{
            Name: "--drag-thumbnail",
            Type: "",
            Dest: "DragThumbnail",
            Help: "Path to an image to use as the drag icon when starting a drag. Must be in PNG/JPEG/GIF/WEBP formats. Other formats will require the presence of ImageMagick on the system to load the image. If not specified, an image is derived based on the data being dragged.",
        })
ans.Add(cli.OptionSpec{
            Name: "--drag-thumbnail-size",
            Type: "int",
            Dest: "DragThumbnailSize",
            Help: "The thumbnail size for the image used as the drag icon. Images larger than this size are downscaled. Note that the terminal may reject the drag if the image is too large.",
        
	Default: "512",
})
ans.Add(cli.OptionSpec{
            Name: "--exit-on",
            Type: "",
            Dest: "ExitOn",
            Help: "A comma separated list of events to exit on. Possible events are :code:`drag-finish`, :code:`drop-finish` and :code:`esc-key`. The first two events refer to a successful completion of a drag or a drop respectively. :code:`esc-key` means press the :kbd:`Esc` key.",
        
	Default: "esc-key",
})
ans.ArgCompleter = cli.MimepatCompleter("Files", cli.CWD, "*")
}
type Options struct {
Drag []string
Drop []string
DropDest string
ConfirmDropOverwrite bool
DropAnywhere string
DragThumbnail string
DragThumbnailSize int
ExitOn string
}
func (opts Options) AsCommandLine() (ans []string) {
	 sval := ""
	 _ = sval
		for _, x := range opts.Drag { ans = append(ans, `--drag=` + x) }
		for _, x := range opts.Drop { ans = append(ans, `--drop=` + x) }
	sval = opts.DropDest
	if (sval != "") { ans = append(ans, `--drop-dest=` + sval)}
	sval = fmt.Sprintf(`%#v`, opts.ConfirmDropOverwrite)
	if (sval != `false`) { ans = append(ans, `--confirm-drop-overwrite=` + sval)}
	sval = opts.DropAnywhere
	if (sval != "disallowed") { ans = append(ans, `--drop-anywhere=` + sval)}
	sval = opts.DragThumbnail
	if (sval != "") { ans = append(ans, `--drag-thumbnail=` + sval)}
	sval = fmt.Sprintf(`%d`, opts.DragThumbnailSize)
	if (sval != `512`) { ans = append(ans, `--drag-thumbnail-size=` + sval)}
	sval = opts.ExitOn
	if (sval != "esc-key") { ans = append(ans, `--exit-on=` + sval)}
return
}
