// Code generated by go_code.py; DO NOT EDIT.

package choose_files

// Total number of bits used: 64
type CombinedScore uint64

func (s CombinedScore) Index() uint32 {
    return uint32(s & 0b11111111111111111111111111111111)
}

func (s *CombinedScore) Set_index(val uint32) {
    *s &^= 0b11111111111111111111111111111111
    *s |= CombinedScore(val & 0b11111111111111111111111111111111)
}

func (s CombinedScore) Length() uint16 {
    return uint16((s >> 32) & 0b1111111111111111)
}

func (s *CombinedScore) Set_length(val uint16) {
    *s &^= 0b1111111111111111 << 32
    *s |= CombinedScore(val&0b1111111111111111) << 32
}

func (s CombinedScore) Score() uint16 {
    return uint16((s >> 48) & 0b1111111111111111)
}

func (s *CombinedScore) Set_score(val uint16) {
    *s &^= 0b1111111111111111 << 48
    *s |= CombinedScore(val&0b1111111111111111) << 48
}

